[package]
name = "tokio-dns"
version = "0.1.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]

[dependencies]
futures = "0.1.1"
futures-cpupool = "0.1.1"
lazy_static = "0.2"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
log = "0.3"
